name: code

on:
  pull_request:
    branches: [ main ]

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
  
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: tests
      run: go test -timeout 30s -v ./... 

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: |
          pip3 install black
          find -name *.py | xargs black --check

  jsonnet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: compile
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest
          sh build/scripts/config/compile.sh
