name: code

on:
  pull_request:
    branches: [ main ]

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
  
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: tests
      run: go test -timeout 30s -v ./... 

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.49

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: |
          pip3 install black
          find -name *.py | xargs black --check

  proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
