name: release_please

on:
  push:
    branches:
      - main

jobs:
  release_please:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: release-please-action
          # beta changes are v0.x
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
