name: release_please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release_please:
    permissions:
      contents: write # create release commit
      pull-requests: write # create release PR

    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f  # v4.1.3
        with:
          release-type: go
          package-name: release-please-action
