name: release_please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release_please:
    permissions:
      contents: write # create release commit
      pull-requests: write # create release PR

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: release-please-action
